version: '3.8'

services:
  openfga:
    image: openfga/openfga:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    command: run

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    command: start-dev --hostname=localhost --hostname-strict=false --http-enabled=true --proxy-headers=xforwarded --spi-cors-enabled=true --spi-cors-origins=http://localhost:3001 --spi-cors-methods=POST,PUT,DELETE,GET,OPTIONS --spi-cors-headers=Authorization,Content-Type,Accept --spi-cors-credentials=true --spi-cors-max-age=3600

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4318:4318"
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml
    command: --config /etc/otel/config.yaml 